CREATE TABLE Recetas (
  ID SERIAL PRIMARY KEY,
  Nombre VARCHAR(25) NOT NULL UNIQUE,
  Imagen VARCHAR(255) NOT NULL,
  ResumenDelPlato TEXT NOT NULL,
  HealthScore FLOAT NOT NULL,
  Pasos TEXT NOT NULL
);

CREATE TABLE Dietas (
  ID SERIAL PRIMARY KEY,
  Nombre VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE RecetasDietas (
  ID SERIAL PRIMARY KEY,
  ID_Recetas INT NOT NULL,
  ID_Dietas INT NOT NULL,
  FOREIGN KEY (ID_Recetas) REFERENCES Recetas(ID),
  FOREIGN KEY (ID_Dietas) REFERENCES Dietas(ID)
);
